workflows:
  ios-release:
    name: iOS Release
    integrations:
      app_store_connect: CM Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.insightshoroscope.astrology

      vars:
        XCODE_PROJECT: "MyHoroscope2.xcodeproj"
        XCODE_SCHEME: "MyHoroscope2"
        BUNDLE_ID: "com.insightshoroscope.astrology"
        APP_STORE_APPLE_ID: 6816404624

      xcode: latest

    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration

        submit_to_testflight: false
