workflows:
  ios-release:
    name: iOS Release
    integrations:
      app_store_connect: CM Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.insightshoroscope.astrology

      vars:
        XCODE_PROJECT: "MyHoroscope2.xcodeproj"
        XCODE_SCHEME: "MyHoroscope2"

      xcode: latest

    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

    publishing:
      app_store_connect:
        auth: integration

        submit_to_testflight: true
